KEYS_ORION = {
    "intensity": [],
    "one-hot": [
        "CD45+",
        "CD68+",
        "CD163+",
        "CD3e+",
        "CD8a+",
        "CD45R0+",
        "CD20+",
        "CD4+",
        "FOXP3+",
        "PDL1+",
        "PD1+",
        "Ki67+",
        "PanCK+",
        "Ecadherin+",
        "CD31+",
        "SMA+",
    ],
}
KEYS_MIPHE = {
    "intensity": [],
    "one-hot": [
        "CD45+",
        "CD68+",
        "CD163+",
        "CD3e+",
        "CD8a+",
        "CD45R0+",
        "CD20+",
        "CD4+",
        "FOXP3+",
        "PDL1+",
        "Ki67+",
        "PanCK+",
        "Ecadherin+",
        "CD31+",
        "SMA+",
        "PD1+",
        "ALL-",
    ],
}
KEYS_MIPHE_PRED = {
    "intensity": [
        "CD31_pred",
        "CD45_pred",
        "CD68_pred",
        "CD4_pred",
        "FOXP3_pred",
        "CD8a_pred",
        "CD45RO_pred",
        "CD20_pred",
        "PD-L1_pred",
        "SMA_pred",
    ],
    "one-hot": [
        "CD45+",
        "CD68+",
        "CD163+",
        "CD3e+",
        "CD8a+",
        "CD45R0+",
        "CD20+",
        "CD4+",
        "FOXP3+",
        "PDL1+",
        "Ki67+",
        "PanCK+",
        "Ecadherin+",
        "CD31+",
        "SMA+",
    ],
}

KEYS_TIPIT = {
    "one-hot": [
        "OX40+",
        "CK+",
        "41BB+",
        "PDL1+",
        "CD3+",
        "TIM3+",
        "PD1+",
        "LAG3+",
        "CD3+/PD1+",
        "CD3+/LAG3+",
        "CD3+/PD1+/LAG3+",
        "CD3+/TIM3+",
        "CD3+/TIM3+/LAG3+",
        "CD3+/TIM3+/PD1+",
        "CD3+/TIM3+/LAG3+/PD1+",
        "MCH II+",
        "CD11c+",
        "OX40L+",
        "CD45R0+",
        "CD4+",
        "FOXP3+",
        "CD8+",
        "CD20+",
        "DC LAMP+",
        "PNAd+",
        "CD21+",
        "DAPI Positive Classification",
        "DAPI Positive Nucleus Classification",
        "Tumor+",
    ],
    "intensity": [
        "Autofluorescence Cell Intensity",
        "DAPI Cell Intensity",
        "OX40 Cell Intensity",
        "CK Cell Intensity",
        "41BB Cell Intensity",
        "PDL1 Cell Intensity",
        "CD3 Cell Intensity",
        "TIM3 Cell Intensity",
        "PD1 Cell Intensity",
        "LAG3 Cell Intensity",
        "MCH Cell Intensity",
        "CD11c Cell Intensity",
        "OX40L Cell Intensity",
        "CD45RO Cell Intensity",
        "CD4 Cell Intensity",
        "FOXP3 Cell Intensity",
        "CD8 Cell Intensity",
        "CD20 Cell Intensity",
        "pnad Cell Intensity",
        "DC Cell Intensity",
        "CD21 Cell Intensity",
        "Cell Area",
        "Cytoplasm Area",
        "Nucleus Area",
        "Nucleus Perimeter",
        "Nucleus Roundness",
    ],
}
